{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "radarr.serviceAccountName" . }}
  labels:
{{ include "radarr.labels" . | indent 4 }}
{{- end -}}
