{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  labels:
{{ include "nextcloud.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  db-password: {{ default "" .Values.mariadb.db.password | b64enc | quote }}
  db-username: {{ default "" .Values.mariadb.db.user | b64enc | quote }}
  {{- else }}
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  db-username: {{ default "" .Values.externalDatabase.user | b64enc | quote }}
  {{- end }}
{{- end }}
