{{- if .Values.nextcloud.phpConfigs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nextcloud.fullname" . }}-phpconfig
  labels:
{{ include "nextcloud.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.nextcloud.phpConfigs }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
