apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
{{ include "nextcloud.labels" . | indent 4 }}
type: Opaque
data:
  nextcloud-username: {{ .Values.nextcloud.username | b64enc | quote }}
  {{ if .Values.nextcloud.password }}
  nextcloud-password: {{ .Values.nextcloud.password | b64enc | quote }}
  {{ else }}
  nextcloud-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{- if .Values.nextcloud.mail.enabled }}
  smtp-username: {{ default "" .Values.nextcloud.mail.smtp.name | b64enc | quote }}
  smtp-password: {{ default "" .Values.nextcloud.mail.smtp.password | b64enc | quote }}
  {{- end }}
