{{- $_ := set . "appName" "nats" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: {{ .appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: nats
      port: 9233
      protocol: TCP
    # TODO: NATS does not currently provide a debug port, re-enable this once that is implemented
    # - name: metrics-debug
    #   port: 9234
    #   protocol: TCP
