{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jackett.serviceAccountName" . }}
  labels:
{{ include "jackett.labels" . | indent 4 }}
{{- end -}}
