apiVersion: v2
name: authelia
type: application
description: A full-featured authentication server
appVersion: "v3.16.2"
version: 1.0.4
keywords:
  - security
  - totp
  - authentication
  - ldap
home: https://www.authelia.com
icon: https://raw.githubusercontent.com/clems4ever/authelia/master/images/authelia.logo.png
sources:
  - https://github.com/clems4ever/authelia
maintainers:
  - name: ishioni
    email: helm@movishell.pl
dependencies:
- name: mongodb
  version: ~7.8.10
  repository: https://charts.helm.sh/stable
  condition: mongodb.enabled
- name: redis
  version: ~10.5.7
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
