apiVersion: v2
name: authelia
type: application
description: A full-featured authentication server
appVersion: 3.16.2
version: 1.0.0
keywords:
  - security
  - totp
  - authentication
  - ldap
home: https://www.authelia.com
icon: https://raw.githubusercontent.com/clems4ever/authelia/master/images/authelia.logo.png
sources:
  - https://github.com/clems4ever/authelia
maintainers:
  - name: ishioni
    email: helm@movishell.pl
