dependencies:
- name: mongodb
  version: ~7.4.6
  repository: https://charts.helm.sh/stable
  condition: mongodb.enabled
- name: redis
  version: ~10.0.1
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
