{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if $officeSuite.enabled }}
{{- $_ := set $ "appName"  (print "app-provider-" (regexReplaceAll "\\W+" (lower $officeSuite.name) "_")) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.appName }}
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    app: {{ $.appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" $ | nindent 4 }}
spec:
  selector:
    app:  {{ $.appName }}
  ports:
    - name: grpc
      port: 9164
      protocol: TCP
    - name: metrics-debug
      port: 9165
      protocol: TCP
{{ end }}
{{ end }}
{{ end }}
