{{- $_ := set . "appName" "graph" -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.graph.resources) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .appName }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["graph", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GRAPH_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: GRAPH_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: GRAPH_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: GRAPH_DEBUG_PPROF
              value: "{{ .Values.debug.profiling }}"

            - name: GRAPH_HTTP_ADDR
              value: 0.0.0.0:9120
            - name: GRAPH_DEBUG_ADDR
              value: 0.0.0.0:9124

            - name: GRAPH_SPACES_WEBDAV_BASE
              value: "https://{{ .Values.externalDomain }}"

            {{ if not .Values.features.externalUserManagement.enabled }}
            - name: GRAPH_LDAP_URI
              value: ldaps://idm:9235
            - name: GRAPH_LDAP_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca.crt
            - name: GRAPH_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: graph-ldap-bind-password
            {{ else }}
            - name: LDAP_URI
              value: {{ .Values.features.externalUserManagement.ldap.uri }}
            - name: LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN }}
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: graph-ldap-bind-password
            - name: GRAPH_LDAP_SERVER_WRITE_ENABLED
              value: "false"
            - name: LDAP_CACERT
              {{ if or (not .Values.features.externalUserManagement.enabled) (not .Values.features.externalUserManagement.ldap.certTrusted) }}
              value: /etc/ocis/ldap-ca/ldap-ca.crt
              {{ else }}
              value: "" # no cert needed
              {{ end }}
            - name: LDAP_INSECURE
              value: "{{ .Values.features.externalUserManagement.ldap.insecure }}"

            - name: LDAP_USER_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN }}
            - name: LDAP_GROUP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.group.baseDN }}

            - name: LDAP_USER_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope }}
            - name: LDAP_GROUP_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.group.scope }}

            - name: LDAP_USER_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter }}
            - name: LDAP_GROUP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.group.filter }}

            - name: LDAP_USER_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass }}
            - name: LDAP_GROUP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.group.objectClass }}

            - name: LDAP_USER_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id }}
            - name: LDAP_GROUP_SCHEMA_ID
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.id }}

            - name: LDAP_USER_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail }}
            - name: LDAP_GROUP_SCHEMA_MAIL
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.mail }}

            - name: LDAP_USER_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.displayName }}
            - name: LDAP_GROUP_SCHEMA_DISPLAYNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.displayName }}

            - name: LDAP_USER_SCHEMA_USERNAME
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName }}
            - name: LDAP_GROUP_SCHEMA_GROUPNAME
              value: {{ .Values.features.externalUserManagement.ldap.group.schema.groupName }}
            {{ end }}


            - name: REVA_GATEWAY
              value: gateway:9142
            - name: GRAPH_EVENTS_ENDPOINT
              value: nats:9233

            - name: GRAPH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9120
            - name: metrics-debug
              containerPort: 9124
          {{ if not .Values.features.externalUserManagement.enabled }}
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
          {{ end }}
      {{ if not .Values.features.externalUserManagement.enabled }}
      volumes:
        - name: ocis-config-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
      {{ end }}
