apiVersion: v2
name: mosquitto
type: application
description: Eclipse Mosquitto - An open source MQTT broker
appVersion: 2.0.3
version: 1.0.0
keywords:
  - message queue
  - MQTT
  - mosquitto
  - eclipse-iot
home: https://mosquitto.org/
icon: https://mosquitto.org/images/mosquitto-text-side-28.png
sources:
  - https://github.com/eclipse/mosquitto
maintainers:
  - name: ishioni
    email: helm@movishell.pl
