# Default values for local-path-provisioner.

service:
  target: some-service.namespace
  port: 80
  targetPort: 80
  protocol: TCP

ingress:
  enabled: false
  annotations: {}
  hostname: example.local
