# Default values for local-path-provisioner.

service:
  target: some-service.namespace
  port: 80
  protocol: TCP

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
