{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "authelia.serviceAccountName" . }}
  labels:
{{ include "authelia.labels" . | indent 4 }}
{{- end -}}
