{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sonarr.serviceAccountName" . }}
  labels:
{{ include "sonarr.labels" . | indent 4 }}
{{- end -}}
