apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "unifi.fullname" . }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := .Values.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "unifi.name" . }}
    helm.sh/chart: {{ include "unifi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "unifi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "unifi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https-gui
              containerPort: 8443
              protocol: TCP
            - name: controller
              containerPort: 8080
              protocol: TCP
            - name: discovery
              containerPort: 10001
              protocol: UDP
            - name: stun
              containerPort: 3478
              protocol: UDP
              {{ if .Values.captivePortalService.enabled }}
            - name: captive-http
              containerPort: 8880
              protocol: TCP
            - name: captive-https
              containerPort: 8843
              protocol: TCP
              {{ end }}
          {{- if not .Values.runAsRoot }}
          securityContext:
            capabilities:
              add:
                - SETFCAP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /status
              port: https-gui
              scheme: HTTPS
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /status
              port: https-gui
              scheme: HTTPS
            initialDelaySeconds: 15
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: RUNAS_UID0
              value: "{{ .Values.runAsRoot }}"
            - name: PUID
              value: "{{ .Values.UID }}"
            - name: PGID
              value: "{{ .Values.GID }}"
            {{- if .Values.extraJvmOpts }}
            - name: JVM_EXTRA_OPTS
              value: "{{- join " " .Values.extraJvmOpts }}"
            {{- end }}
            - name: JVM_INIT_HEAP_SIZE
              value: "{{ .Values.jvmInitHeapSize }}"
            - name: JVM_MAX_HEAP_SIZE
              value: "{{ .Values.jvmMaxHeapSize }}"
            {{- if .Values.mongodb.enabled }}
            - name: DB_MONGO_LOCAL
              value: "false"
            - name: DB_MONGO_URI
              value: "{{ .Values.mongodb.dbUri }}"
            - name: STATDB_MONGO_URI
              value: "{{ .Values.mongodb.statDbUri }}"
            - name: UNIFI_DB_NAME
              value: "{{ .Values.mongodb.databaseName }}"
            {{- end }}
          volumeMounts:
            - mountPath: /usr/lib/unifi/data
              name: unifi-data
              subPath: data
            - mountPath: /usr/lib/unifi/logs
              name: unifi-data
              subPath: logs
            - mountPath: /usr/lib/unifi/cert
              name: unifi-data
              subPath: cert
            {{- if .Values.extraConfigFiles }}
            - name: extra-config
              mountPath: /configmap
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: unifi-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "unifi.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{ end }}
        {{- if .Values.extraConfigFiles }}
        - name: extra-config
          configMap:
            name: {{ template "unifi.fullname" . }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
