{{- if .Values.persistence.data.enabled -}}
{{- if eq .Values.persistence.data.type "pvc" -}}
{{- if not .Values.persistence.data.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "transmission.fullname" . }}-data
  labels:
{{ include "transmission.labels" . | indent 4 }}
{{- if .Values.persistence.data.annotations }}
  annotations:
{{ toYaml .Values.persistence.data.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
