apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
{{ include "transmission.labels" . | indent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "transmission.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peertcp
  labels:
{{ include "transmission.labels" . | indent 4 }}
{{- with .Values.service.peerPort.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.peerPort.type }}
{{- if (eq .Values.service.peerPort.type "LoadBalancer") }}
  {{- if .Values.service.peerPort.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.peerPort.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.peerPort.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.peerPort.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- end }}
{{- if .Values.service.peerPort.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.peerPort.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.peerPort.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.peerPort.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.service.peerPort.port }}
      targetPort: utp-tcp
      protocol: TCP
      name: utp-tcp
{{ if (eq .Values.service.peerPort.type "NodePort") }}
      nodePort: {{ .Values.service.peerPort.port }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "transmission.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peerudp
  labels:
{{ include "transmission.labels" . | indent 4 }}
{{- with .Values.service.peerPort.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.peerPort.type }}
{{- if (eq .Values.service.peerPort.type "LoadBalancer") }}
  {{- if .Values.service.peerPort.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.peerPort.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.peerPort.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.peerPort.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- end }}
{{- if .Values.service.peerPort.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.peerPort.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.peerPort.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.peerPort.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.service.peerPort.port }}
      targetPort: utp-udp
      protocol: UDP
      name: utp-udop
{{ if (eq .Values.service.peerPort.type "NodePort") }}
      nodePort: {{ .Values.service.peerPort.port }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "transmission.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
