apiVersion: v1
name: radarr
version: 0.1.0
appVersion: "2.0.0.5337"
description: A fork of Sonarr to work with movies à la Couchpotato.
keywords:
  - p2p
  - movies
home: https://radarr.video
icon: https://raw.githubusercontent.com/Radarr/Radarr/aphrodite/Logo/256.png
sources:
- https://github.com/Radarr/Radarr
