apiVersion: v2
name: nextcloud
type: application
description: A file sharing server that puts the control and security of your own data back into your hands.
version: 1.11.0
appVersion: 20.0.3
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
sources:
  - https://github.com/nextcloud/docker
maintainers:
  - name: ishioni
    email: helm@movishell.pl
