{{- if .Values.dynmap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "minecraft.fullname" . }}-dynmap
  labels:
{{ include "minecraft.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: dynmap
      protocol: TCP
      name: dynmap
  selector:
    app.kubernetes.io/name: {{ include "minecraft.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
