{{- if .Values.dynmap.enabled -}}
{{- $fullName := include "minecraft.fullname" . -}}
{{- $svcPort := "dynmap" -}}
apiVersion: {{ include "minecraft.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "minecraft.labels" . | indent 4 }}
  {{- with .Values.dynmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.dynmap.tls }}
  tls:
  {{- range .Values.dynmap.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.dynmap.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            {{- if eq (include "minecraft.ingress.apiVersion" $) "networking.k8s.io/v1" }}
            pathType: Prefix
            {{- end }}
            backend:
            {{- if eq (include "minecraft.ingress.apiVersion" $) "networking.k8s.io/v1" }}
              service:
                name: {{ $fullName }}-dynmap
                port:
                  number: {{ $svcPort }}
            {{- else }}
              serviceName: {{ $fullName }}-dynmap
              servicePort: {{ $svcPort }}
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
