apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minecraft.fullname" . }}
  labels:
{{ include "minecraft.labels" . | indent 4 }}
type: Opaque
data:
  rcon-password: {{ default "" .Values.minecraftServer.rcon.password | b64enc | quote }}
