{{- $_ := set . "appName" "settings" -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.settings.resources) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .appName }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      securityContext:
          fsGroup: {{ .Values.securityContext.fsGroup }}
          fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["settings", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: SETTINGS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: SETTINGS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: SETTINGS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: SETTINGS_DEBUG_PPROF
              value: "{{ .Values.debug.profiling }}"

            - name: SETTINGS_HTTP_ADDR
              value: 0.0.0.0:9190
            - name: SETTINGS_GRPC_ADDR
              value: 0.0.0.0:9191
            - name: SETTINGS_DEBUG_ADDR
              value: 0.0.0.0:9194

            - name: STORAGE_GATEWAY_GRPC_ADDR
              value: storage-system:9215
            - name: STORAGE_GRPC_ADDR
              value: storage-system:9215

            - name: SETTINGS_ADMIN_USER_ID
            {{- if .Values.features.externalUserManagement.enabled }}
              value: {{ .Values.features.externalUserManagement.adminUUID }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.adminUserSecretRef }}
                  key: user-id
            {{- end }}

            - name: SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: OCIS_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: api-key
            - name: OCIS_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storageSystemSecretRef }}
                  key: user-id

          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9190
            - name: grpc
              containerPort: 9191
            - name: metrics-debug
              containerPort: 9194
