apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.netdata.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ toYaml $config.data | indent 4 }}
  {{- end }}
  {{- end }}
