{{- $_ := set . "appName" "idm" -}}
{{- if not .Values.features.externalUserManagement.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  namespace: {{ template "ocis.namespace" . }}
  labels:
    app: {{ .appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .appName }}
  ports:
    - name: ldaps
      port: 9235
      protocol: TCP
    # TODO: IDM does not currently provide a debug port, re-enable this once that is implemented
    # - name: metrics-debug
    #   port: 9239
    #   protocol: TCP
{{- end }}
